# Generated by Django 3.1.1 on 2022-12-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221225_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shares',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='shares',
            old_name='value',
            new_name='description',
        ),
        migrations.AddField(
            model_name='shares',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='followings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followuser',
            name='followers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='images',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shares',
            name='private',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shares',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='interest',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='occupation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='security_question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
