# Generated by Django 4.1.3 on 2022-11-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0019_auto_20190718_2048"),
    ]

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("security_question", models.CharField(max_length=100)),
                ("answer", models.CharField(max_length=20)),
            ],
            options={"db_table": "db_users",},
        ),
    ]
