# Generated by Django 3.1.1 on 2022-12-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20221218_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.CharField(max_length=255),
        ),
    ]
