# Generated by Django 3.1.1 on 2022-12-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
