# Generated by Django 3.1.1 on 2022-12-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20221208_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subjects',
        ),
    ]
