# Generated by Django 3.1.1 on 2022-12-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shares',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shares',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shares',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
