version: "3.8"
services:
  app:
    build: .  # build from Dockerfile in current directory
    volumes:
      - .:/app  #  
    ports:
      - "8000:8000"  # map port 8000 on host to port 8000 in container
    image: app:latest  # tag the image as app:latest
    container_name: ihub  # name the container as swe573_term_project
    command: python manage.py runserver 0.0.0.0:8000  # run the command to start the server
    depends_on:
      - db  # start the db
  db:
    image: mysql:latest  # use the latest postgres image
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'swe_573'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306  # cannot change this port to other number
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER : root
    ports:
      - "3306:3306"  # map port 8000 on host to port 8000 in container
    container_name: mysql_db